[project]
name = "yt_find_peak"
version = "0.1.0"
description = "Find peak YouTube video"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.14.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]

[tool.ruff]
line-length = 120
