[project]
name = "yt_find_peak"
version = "0.1.0"
description = "Find peak YouTube video"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scipy>=1.14.1",
]

[tool.uv]
dev-dependencies = [
    "matplotlib>=3.9.2",
    "ruff>=0.6.9",
]

[tool.ruff]
line-length = 120
